# Generated by Django 3.2.5 on 2021-07-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_gifts', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('bonus', models.TextField()),
                ('properties', models.JSONField(blank=True, default='{}', null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_bg_image_id', models.BigIntegerField(blank=True, null=True)),
                ('cost_freecoins', models.IntegerField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('icon_bg_image_id', models.CharField(blank=True, max_length=191, null=True)),
                ('image2', models.CharField(blank=True, max_length=200, null=True)),
                ('days_to_accept', models.SmallIntegerField(default='1')),
            ],
            options={
                'verbose_name_plural': 'Gifts',
                'db_table': 'gifts',
                'managed': False,
            },
        ),
    ]
